title: Rakshith Ramureddy

description: |
  Email: rakshithreddy2012@gmail.com
  Mobile: +44 75088 79149
  LinkedIn: https://www.linkedin.com/in/rakshith-ramureddy-25020010b

work_experience:
  - title: Store Assistant and Inventory Management
    company: Clarks Bakery
    location: Dundee, UK
    duration: 03/2023 – Current

  - title: Telecom Engineer
    company: Movate
    location: India
    duration: 12/2021 – 12/2022

  - title: Process Consultant
    company: Hinduja Global Solutions
    location: India
    duration: 08/2019 – 11/2021

show_downloads: false
theme: jekyll-theme-minimal

