title: Rakshith Ramureddy
logo: /assets/img/1706038002233.jpeg
description: Aspiring Business Analyst with a strong foundation in data analytics, process optimization, and customer engagement. With hands-on experience in both technical and customer-facing roles, I excel in leveraging data to drive strategic business solutions and operational efficiency.

show_downloads: false
theme: jekyll-theme-cayman
