title: Rakshith Ramureddy
description: |
  Email: [rakshithreddy2012@gmail.com](mailto:rakshithreddy2012@gmail.com)  
  **Mobile:** +44 75088 79149  
  **LinkedIn:** [Rakshith Ramureddy](https://www.linkedin.com/in/rakshith-ramureddy-25020010b)
  
  **Work Experience:**
  - **Store Assistant and Inventory Management**  
    *Clarks Bakery, Dundee, UK*  
    *03/2023 – Current*

  - **Telecom Engineer**  
    *Movate, India*  
    *12/2021 – 12/2022*

  - **Process Consultant**  
    *Hinduja Global Solutions, India*  
    *08/2019 – 11/2021*

show_downloads: true
theme: jekyll-theme-minimal
