title: Rakshith Ramureddy
tagline: Data Analyst | MSc Business Analytics | SQL | Power BI | Python
description: >-
  MSc Business Analytics graduate with 4+ years of experience in data analysis, stakeholder reporting, and technical support.
  Skilled in SQL, Power BI, Python, and data governance. Delivered KPI dashboards, root cause analyses, and statutory reporting across sectors.

show_downloads: false
theme: jekyll-theme-cayman

markdown: kramdown

kramdown:
  parse_block_html: true

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
      markdown: kramdown
      render_with_liquid: true
